[CmdletBinding()]
param(
    # Project root (folder containing the .uproject) to link the plugin into.
    # With -Create, this is instead the destination path for a brand-new project.
    [string] $ProjectDir,

    # Create a new project at -ProjectDir before setting it up (Stage 0). Without this,
    # -ProjectDir must already contain a .uproject and behaviour is unchanged.
    [switch] $Create,

    # Project / module name for -Create (defaults to the -ProjectDir leaf folder).
    [string] $ProjectName,

    # Default graphics RHI for a -Create project (forwarded to create_project; defaults to D3D12).
    [ValidateSet('D3D12', 'D3D11', 'Vulkan')]
    [string] $Rhi,

    # RenderStream scene-selection mode for a -Create project (forwarded to create_project).
    [ValidateSet('None', 'Maps', 'StreamingLevels')]
    [string] $Mode,

    # Name of the plugin folder created under the project's Plugins dir (defaults to the repo folder name).
    [string] $PluginName,

    # Delete an existing real plugin folder instead of backing it up (forwarded to link_to_project).
    [switch] $NoBackup,

    # Generate a Visual Studio .sln instead of VS Code files (forwarded to generate_project_files).
    [switch] $VisualStudio,

    # Include full engine source in the workspace (forwarded to generate_project_files).
    [switch] $IncludeEngine,

    # Open the generated workspace when done (forwarded to generate_project_files).
    [switch] $Open,

    # Skip regenerating the .uplugin (e.g. it was already generated by the post-checkout hook).
    [switch] $SkipUplugin,

    # Run the headless bake (build the editor target + generate the test scene's maps +
    # RenderStream schema). Opt-in - the bake is skipped unless this is passed.
    [switch] $Bake,

    # Print usage and exit.
    [switch] $Help
)

$ErrorActionPreference = 'Stop'

if ($Help) {
    Write-Host @"
Usage: setup_dev_environment.ps1 -ProjectDir <path> [options]

Sets up an Unreal project to develop the RenderStream plugin against, optionally
creating a fresh RenderStream test project first. Runs: create (optional) -> generate
.uplugin -> link plugin -> generate project files -> headless bake (with -Bake).

  -ProjectDir <path>      Project folder to set up; with -Create, the destination for the new project.
  -Create                 Create a fresh RenderStream test project at -ProjectDir before setup.
  -ProjectName <name>     Project/module name for -Create (defaults to the -ProjectDir folder name).
  -Rhi <D3D12|D3D11|Vulkan>          Default graphics RHI for a -Create project (defaults to D3D12).
  -Mode <None|Maps|StreamingLevels>  RenderStream scene selector for a -Create project (defaults to None).
  -PluginName <name>      Name of the plugin folder created under the project's Plugins (defaults to repo folder).
  -NoBackup               Delete an existing real plugin folder instead of backing it up.
  -VisualStudio           Generate a Visual Studio .sln instead of VS Code files.
  -IncludeEngine          Include full engine source in the generated workspace (heavier).
  -Open                   Open the generated workspace when done.
  -SkipUplugin            Skip regenerating the .uplugin.
  -Bake                   Run the headless bake (build editor target + generate test scene/schema).
  -Help                   Show this help and exit.
"@
    return
}

if (-not $ProjectDir) {
    throw "-ProjectDir is required (run with -Help for usage)."
}

$RepoDir = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }

# generate_uplugin.ps1 reads uplugin_template.json by relative path, so run from the repo dir.
# Child powershell processes inherit this working directory.
Push-Location $RepoDir
try {
    function Invoke-Step {
        param([string] $Title, [string] $Script, [string[]] $ScriptArgs = @())

        Write-Host ""
        Write-Host "==== $Title ====" -ForegroundColor Magenta
        & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $Script @ScriptArgs
        if ($LASTEXITCODE -ne 0) {
            throw "$Title failed (exit code $LASTEXITCODE). Aborting setup."
        }
    }

    # 0) Optionally create the project from scratch before the standard setup steps.
    if ($Create) {
        $createArgs = @('-ProjectDir', $ProjectDir)
        if ($ProjectName) { $createArgs += @('-ProjectName', $ProjectName) }
        if ($Rhi)         { $createArgs += @('-Rhi', $Rhi) }
        if ($Mode)        { $createArgs += @('-Mode', $Mode) }
        Invoke-Step 'Create project' (Join-Path $RepoDir 'create_project.ps1') $createArgs
    }

    # 1) Generate the .uplugin from the template.
    if (-not $SkipUplugin) {
        Invoke-Step 'Generate .uplugin' (Join-Path $RepoDir 'generate_uplugin.ps1')
    } else {
        Write-Host "Skipping .uplugin generation (-SkipUplugin)." -ForegroundColor DarkGray
    }

    # 2) Junction-link the repo into the project's Plugins folder.
    $linkArgs = @('-ProjectDir', $ProjectDir)
    if ($PluginName) { $linkArgs += @('-PluginName', $PluginName) }
    if ($NoBackup)   { $linkArgs += '-NoBackup' }
    Invoke-Step 'Link to project' (Join-Path $RepoDir 'link_to_project.ps1') $linkArgs

    # 3) Generate IDE project files for the linked project.
    $genArgs = @('-ProjectDir', $ProjectDir)
    if ($VisualStudio)  { $genArgs += '-VisualStudio' }
    if ($IncludeEngine) { $genArgs += '-IncludeEngine' }
    if ($Open)          { $genArgs += '-Open' }
    Invoke-Step 'Generate project files' (Join-Path $RepoDir 'generate_project_files.ps1') $genArgs

    # 4) Opt-in: build the editor target and bake the test scene (maps + RS schema).
    if ($Bake) {
        Invoke-Step 'Bake test scene' (Join-Path $RepoDir 'bake_project.ps1') @('-ProjectDir', $ProjectDir)
    }

    Write-Host ""
    Write-Host "Dev environment ready." -ForegroundColor Green
}
finally {
    Pop-Location
}
