[CmdletBinding()]
param(
    # Project root (folder containing the .uproject) to link the plugin into.
    [Parameter(Mandatory = $true)]
    [string] $ProjectDir,

    # Name of the plugin folder created under the project's Plugins dir (defaults to the repo folder name).
    [string] $PluginName,

    # Delete an existing real plugin folder instead of backing it up (forwarded to link_to_project).
    [switch] $NoBackup,

    # Generate a Visual Studio .sln instead of VS Code files (forwarded to generate_project_files).
    [switch] $VisualStudio,

    # Include full engine source in the workspace (forwarded to generate_project_files).
    [switch] $IncludeEngine,

    # Open the generated workspace when done (forwarded to generate_project_files).
    [switch] $Open,

    # Skip regenerating the .uplugin (e.g. it was already generated by the post-checkout hook).
    [switch] $SkipUplugin
)

$ErrorActionPreference = 'Stop'

$RepoDir = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }

# generate_uplugin.ps1 reads uplugin_template.json by relative path, so run from the repo dir.
# Child powershell processes inherit this working directory.
Push-Location $RepoDir
try {
    function Invoke-Step {
        param([string] $Title, [string] $Script, [string[]] $ScriptArgs = @())

        Write-Host ""
        Write-Host "==== $Title ====" -ForegroundColor Magenta
        & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $Script @ScriptArgs
        if ($LASTEXITCODE -ne 0) {
            throw "$Title failed (exit code $LASTEXITCODE). Aborting setup."
        }
    }

    # 1) Generate the .uplugin from the template.
    if (-not $SkipUplugin) {
        Invoke-Step 'Generate .uplugin' (Join-Path $RepoDir 'generate_uplugin.ps1')
    } else {
        Write-Host "Skipping .uplugin generation (-SkipUplugin)." -ForegroundColor DarkGray
    }

    # 2) Junction-link the repo into the project's Plugins folder.
    $linkArgs = @('-ProjectDir', $ProjectDir)
    if ($PluginName) { $linkArgs += @('-PluginName', $PluginName) }
    if ($NoBackup)   { $linkArgs += '-NoBackup' }
    Invoke-Step 'Link to project' (Join-Path $RepoDir 'link_to_project.ps1') $linkArgs

    # 3) Generate IDE project files for the linked project.
    $genArgs = @('-ProjectDir', $ProjectDir)
    if ($VisualStudio)  { $genArgs += '-VisualStudio' }
    if ($IncludeEngine) { $genArgs += '-IncludeEngine' }
    if ($Open)          { $genArgs += '-Open' }
    Invoke-Step 'Generate project files' (Join-Path $RepoDir 'generate_project_files.ps1') $genArgs

    Write-Host ""
    Write-Host "Dev environment ready." -ForegroundColor Green
}
finally {
    Pop-Location
}
